spring.application.name=TFG-Backend

# Supabase / PostgreSQL
spring.datasource.url=jdbc:postgresql://db.Sergio-no's Project.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Root@1234HS123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ? importante: validate para no tocar la BBDD que ya tienes creada
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# Puerto
server.port=8080

# Firebase ? ruta al fichero de credenciales que descargas de Firebase Console
firebase.credentials.path=classpath:firebase-service-account.json